//Authentication
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const AUTH_FAILED = 'AUTH_FAILED';
export const FORGOT_PASS = 'FORGOT_PASS';
export const FORGOT_PASS_FAILED = 'FORGOT_PASS_FAILED';
export const RESET_PASS = 'RESET_PASS'
export const RESET_PASS_FAILED = 'RESET_PASS_FAILED'
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'

//Profile update Forms
export const UPDATE_FORM = "UPDATE_FORM"
export const UPDATE_FAILED = "UPDATE_FAILED"

//GET PROFILE
export const FETCH_PROFILE = "FETCH_PROFILE"
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED"
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED"
export const RESET_USER_PROFILE = "RESET_USER_PROFILE"

export const GET_MAPPER_SUCCESS = "GET_MAPPER_SUCCESS"
export const GET_MAPPER_FAILED = "GET_MAPPER_FAILED"

export const EXECUTOR_SUCCESS = "EXECUTOR_SUCCESS"
export const EXECUTOR_FAILED = "EXECUTOR_FAILED"

export const GENERATOR_SUCCESS = "GENERATOR_SUCCESS";
export const GENERATOR_FAILED = "GENERATOR_FAILED";
export const GENERATOR_LOADING = "GENERATOR_LOADING";